### ISSUE TITLE
I'm getting this runing Gctf-1.18 in release 2.0

### ISSUE THREAD

**Issue by pconesa** [scipion-em/scipion-em-gctf#13]
All 1 files to be searched and refined:
00154:           Runs/002073_ProtGctf/tmp/mic_0001/20170629_00021_frameImage_aligned_mic_DW.mrc
00155:   Error in function gctf_open_sumlog(), file ctf.cu on line 5252: Cannot open ctfstar file! Check the input!! Exit now!

Any hint?

**Comment by pconesa** [comment]
I had to manually move file inside the tgz....they are uncompressed at root instead of at bin.

**Comment by azazellochg** [comment]
@pconesa you are using the wrong binaries, this was fixed in 1.18b2

**Comment by pconesa** [comment]
Thanks Gregory. We have done many combinations, and last one was using
binaries we distribute, probably they need to be updated with B2 versions.

We also tried downloading them from the website and regularly we were
getting black Images with a white ring. Black is coming from a NaN value.

It's like not able to estimate the CTF for our data acquired here with VPP.

Any idea?

I'll make sure we try with B2 and code from the plugin.

We have tried with 1.2.1 with no success.

**Comment by azazellochg** [comment]
https://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/Gctf_v1.18_b2/bin/ here is b2 binaries where this bug should have been fixed

**Comment by azazellochg** [comment]
@pconesa gctf will fail if you are running a  binary incompatible with your gpu card compute capability. For example, if you have Titan V card, you need to have cc 7.0 or 7.2 meaning you need to run Gctf_v1.18_b2_sm70_cu9.1 

List of cc for GPU cards is here: https://en.wikipedia.org/wiki/CUDA

**Comment by pconesa** [comment]
Thanks Gregory, I always thought a lower one would work with all. I was
wrong!

**Comment by MrGao1997** [comment]
Something wrong when I download the Gctf from https://www.mrc-lmb.cam.ac.uk/kzhang/Gctf/. It is more like the software removed from this website. So do you kown how can I install it. By the way, the cuda is 12.4 in my system, so which one do you recommend to download? Thanks for you advise. @azazellochg

**Comment by azazellochg** [comment]
@MrGao1997 gctf has been deprecated many moons ago, you can still find it at https://scipion.cnb.csic.es/downloads/scipion/software/em/Gctf_v1.18/bin/

**Comment by MrGao1997** [comment]
Really thanks for your sharing!!! Best wishes!




---- Replied Message ----
| From | Grigory ***@***.***> |
| Date | 2/4/2026 18:04 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [scipion-em/scipion-em-gctf] I'm getting this runing Gctf-1.18 in release 2.0 (#13) |
azazellochg left a comment (scipion-em/scipion-em-gctf#13)

@MrGao1997 gctf has been deprecated many moons ago, you can still find it at https://scipion.cnb.csic.es/downloads/scipion/software/em/Gctf_v1.18/bin/
