### ISSUE TITLE
Bug with High resolution refine

### ISSUE THREAD

**Issue by delarosatrevin** [scipion-em/scipion-em-gctf#14]
@azazellochg I think we have a bug here: https://github.com/scipion-em/scipion-em-gctf/pull/12/files#diff-4263160ae0d79c50e7c818a32e0e94e3L518

The format string is %d, but the parameters are float, should I change it to %f?

**Comment by azazellochg** [comment]
You are right, you can fix it in devel directly.

Best regards,
Grigory

--------------------------------------------------------------------------------
Grigory Sharov, Ph.D.

MRC Laboratory of Molecular Biology,
Francis Crick Avenue,
Cambridge Biomedical Campus,
Cambridge CB2 0QH, UK.
tel. +44 (0) 1223 267542 <+44%201223%20267542>
e-mail: gsharov@mrc-lmb.cam.ac.uk

**Comment by azazellochg** [comment]
fixed
