### ISSUE TITLE
Results differs from cuda91 to cuda8 (gctf-v.1.18)

### ISSUE THREAD

**Issue by dmaluenda** [scipion-em/scipion-em-gctf#25]
Hi, I copy an issue received by mail from a user:

The results from Gctf version 1.18 running on cuda91 are considerably worse than from Gctf version 1.18 running on cuda8. Have you seen something similar before?

**Comment by azazellochg** [comment]
No, I haven't seen this. This is not a scipion issue and I would advice to address it to jack.zhang@yale.edu
