### ISSUE TITLE
Gctf plugin is not property getting the results from the binary

### ISSUE THREAD

**Issue by dmaluenda** [scipion-em/scipion-em-gctf#26]
I’m using gctf (installed from the plugin manager) in Scipion2 and it seems working fine but Scipion is not retrieving the parameters (all them are set at -9999.9).

If I check the tmp files they also look right. Any idea?

I get this in the log:

```
Warning in function gctf_open_sumlog(), file src/ctf.cu on line 2965:No output ctfstar file!
You may have to extract CTF information from *_gctf.log!
```

**Comment by azazellochg** [comment]
This means gctf has failed and you are not using right binary / cuda / gpu combination. gctf software is outdated and might not work on your gpu

**Comment by azazellochg** [comment]
@dmaluenda please try new binaries for cuda 10.1 that were just uploaded
