### ISSUE TITLE
Issue in Gctf_v1.18 Scipion 3 using more than 2 threads

### ISSUE THREAD

**Issue by marperezruiz** [scipion-em/scipion-em-gctf#34]
Hi all, 

I am having some issues when I try to run the Gctf protocol in Scipion 3 using more than 2 threads (such us multiple of 2). If I use 2 threads the protocol run perfectly and the ctf is calculated, but, when I use 6, 16 or even 32 it doesn't work. It seems that it is still running but then the values for the ctf correction is wrong (-999.99 for example for defocus values). 

Please, see below the error in run.stdout: 

00001:   RUNNING PROTOCOL -----------------
00002:   Hostname: g-11-g0007.cm.cluster
00003:   PID: 6907
00004:   pyworkflow: 3.0.7
00005:   plugin: gctf
00006:   plugin v: 3.0.11
00007:   currentDir: /home/projects/
00008:   workingDir: Runs/001830_ProtGctf
00009:   runMode: Continue
00010:             MPI: 1
00011:         threads: 6
00012:    Starting at step: 1
00013:    Running steps 
00014:   STARTED: estimateCtfStep, step 1, time 2020-11-25 13:14:35.310467
00015:   STARTED: estimateCtfStep, step 2, time 2020-11-25 13:14:35.327362
00016:   Estimating CTF of micrograph: 1 
00017:   /home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/software/em/gctf-1.18/bin/Gctf_v1.18_b2_sm60_cu8.0  --apix 1.100000 --kV 300.000000 --cs 2.700000 --ac 0.100000 --dstep 8.250000 --defL 5000.000000 --defH 90000.000000 --defS 500.000000 --astm 1000.000000 --resL 50.000000 --resH 4.000000 --do_EPA 0 --boxsize 1024 --plot_res_ring 1 --gid %(GPU)s --bfac 150 --B_resH 2.200000 --overlap 0.500000 --convsize 85 --do_Hres_ref 0 --smooth_resL 1000 --EPA_oversmp 4 --ctfstar NONE --do_validation 0  Runs/001830_ProtGctf/tmp/mic_0001/*.mrc
00018:   STARTED: estimateCtfStep, step 3, time 2020-11-25 13:14:35.567757
00019:   Estimating CTF of micrograph: 2 
00020:   /bin/sh: -c: line 0: syntax error near unexpected token `('
00021:   /bin/sh: -c: line 0: `/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/software/em/gctf-1.18/bin/Gctf_v1.18_b2_sm60_cu8.0  --apix 1.100000 --kV 300.000000 --cs 2.700000 --ac 0.100000 --dstep 8.250000 --defL 5000.000000 --defH 90000.000000 --defS 500.000000 --astm 1000.000000 --resL 50.000000 --resH 4.000000 --do_EPA 0 --boxsize 1024 --plot_res_ring 1 --gid %(GPU)s --bfac 150 --B_resH 2.200000 --overlap 0.500000 --convsize 85 --do_Hres_ref 0 --smooth_resL 1000 --EPA_oversmp 4 --ctfstar NONE --do_validation 0  Runs/001830_ProtGctf/tmp/mic_0001/*.mrc'
00022:   ERROR: Gctf has failed on Runs/001830_ProtGctf/tmp/mic_0001/*.mrc
.
.
.
.
00026:   Traceback (most recent call last):
00027:     File "/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/.scipion3env-sbmm-shared/lib/python3.8/site-packages/gctf/protocols/protocol_gctf.py", line 86, in _estimateCtfList
00028:       self.runJob(program, args)  # , env=gctf.Plugin.getEnviron())
00029:     File "/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/.scipion3env-sbmm-shared/lib/python3.8/site-packages/pyworkflow/protocol/protocol.py", line 1338, in runJob
00030:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00031:     File "/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/.scipion3env-sbmm-shared/lib/python3.8/site-packages/pyworkflow/protocol/executor.py", line 65, in runJob
00032:       process.runJob(log, programName, params,
00033:     File "/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/.scipion3env-sbmm-shared/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 51, in runJob
00034:       return runCommand(command, env, cwd)
00035:     File "/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/.scipion3env-sbmm-shared/lib/python3.8/site-packages/pyworkflow/utils/process.py", line 66, in runCommand
00036:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr,
00037:     File "/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/.scipion3env-sbmm-shared/lib/python3.8/subprocess.py", line 364, in check_call
00038:       raise CalledProcessError(retcode, cmd)
00039:   subprocess.CalledProcessError: Command '/home/projects/cpr_sbmm/apps/scipion3-conda-env-sbmm-gcc5/software/em/gctf-1.18/bin/Gctf_v1.18_b2_sm60_cu8.0  --apix 1.100000 --kV 300.000000 --cs 2.700000 --ac 0.100000 --dstep 8.250000 --defL 5000.000000 --defH 90000.000000 --defS 500.000000 --astm 1000.000000 --resL 50.000000 --resH 4.000000 --do_EPA 0 --boxsize 1024 --plot_res_ring 1 --gid %(GPU)s --bfac 150 --B_resH 2.200000 --overlap 0.500000 --convsize 85 --do_Hres_ref 0 --smooth_resL 1000 --EPA_oversmp 4 --ctfstar NONE --do_validation 0  Runs/001830_ProtGctf/tmp/mic_0001/*.mrc' returned non-zero exit status 1.

Any ideas what would it be wrong?
Thank you in advance,
Best regards,

**Comment by azazellochg** [comment]
Hi @marperezruiz , sorry for the delayed reply. Gctf works only on GPU, so number of threads and number of GPUs must correlate. What do you provide in GPU IDs field? I would not recommend running more than 1 gctf process per GPU, so if you have N GPUs, then provide their IDs and set number of threads to N+1 (extra thread is for the master process).

**Comment by marperezruiz** [comment]
Hi @azazellochg , thank you so much for your reply and explanation. I was using 1 GPU and 2 threads. Now, I understand why when I selected 1 GPU and more than 2 threads the gctf failed. 
Thanks again!

**Comment by azazellochg** [comment]
Thanks for raising the this up! I do need to document these things. If you want to process several mics at a time and have one gpu, I'd suggest using batches, this will reduce the overhead of executing too many steps for each mic
