### ISSUE TITLE
Waring: Invalid resH 4.00!

### ISSUE THREAD

**Issue by DStrelak** [scipion-em/scipion-em-gctf#43]
Maybe this is not an issue, but I have noticed that one of the gCTF tests (`/scipion3 tests gctf.tests.test_protocols_gctf.TestGctf`), more specifically the ProtGctf.75 protocol, runs much longer than ProtGctf.149 (17 s vs. 3 s).
In the output of the former one, I see following warning message, which might be related to it:
/scipion3 tests gctf.tests.test_protocols_gctf.TestGctf 
```
Waring: Invalid resH 4.00! Exit now. Make sure you are using the right value, typically 4.0~8.0 angstrom,and must be smaller than 30.Set it as default 4.0 angstrom.
```

**Comment by azazellochg** [comment]
This (harmless) warning message has been there for very long time. Gctf is closed source, no longer developed or supported, so nobody will fix this. The reason for the longer run of one of the tests is that it does downsampling with xmipp before gctf run.
