### ISSUE TITLE
gctf - ts CTF estimation: it does not set the acquisition order

### ISSUE THREAD

**Issue by JorMaister** [scipion-em/scipion-em-gctf#55]
Hi, @azazellochg. I can do it if you want, but I'd like to redo part of the protocol the same way I did with the ts CTF estimation in Ctffind, to avoid the inheritance from the protocol ProtTsEstimateCTF, as its code is quite old. Only gctf inherits from it. Please let me know your thoughts about it.

**Comment by azazellochg** [comment]
Hi Jorge, please go ahead 🤠
