### ISSUE TITLE
Installation from plugin manager doesn't create the conda env 

### ISSUE THREAD

**Issue by MohamadHarastani** [scipion-em/scipion-em-gctf#59]
Hello cool people

I updated the plugin from the plugin manager on a user computer and the installer didn't create the conda env gctf. It worked when installed it in devel. 

Cheers
Mohamad

**Comment by azazellochg** [comment]
Hi, Mohamad,

I believe the plugin manager cannot tell that now the plugin needs a conda environment. You need to first delete existing binaries and then try again.
